version: '3.8'

services:
  orderdb:
    image: mongo

  messagebroker:
    image: rabbitmq:management

  rediscache:
    image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9

  portainer:
    image: portainer/portainer-ce

  basketservice:
    image: ${DOCKER_REGISTRY-}basketservice
    build:
      context: .
      dockerfile: Basket.Dockerfile

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: Order.Dockerfile

  queueapigateway:
    image: ${DOCKER_REGISTRY-}queueapigateway
    build:
      context: .
      dockerfile: Gateway.Dockerfile

volumes:
  mongo_data:
  portainer_data:  
  elasticsearch_data:   